### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by danb5** [rxseger/homebridge-contactsensor#1]
This is fails to launch when starting homebridge.  It states invalid token.  Any ideas?

**\* I solved this by updating node to versio 6.**\* and reinstalling homebridge. This works fantastic!   I use it with a grove water sensor and have it set to turn off my well pump if it senses a leak and then to turn a hue light bluefin a main room.   This is a fantastic plugin.

**Comment by danb5** [comment]
Here is the errror:
[10/20/2016, 12:26:23 PM] ERROR LOADING PLUGIN homebridge-contactsensor:
[10/20/2016, 12:26:24 PM] SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:129:14)
    at Array.forEach (native)

**Comment by rxseger** [comment]
Glad you got it working! And yeah I'm taking advantage of the latest ES6 features in homebridge-contactsensor (classes, let/const, etc.) so Node 6+ is required (I do specify "node": ">=6.0.0" in the package.json, but node seems to not enforce this requirement.)
