### ISSUE TITLE
Unable to get Plugin to start (error when starting)

### ISSUE THREAD

**Issue by joshua-pe** [rxseger/homebridge-contactsensor#13]
Hello, i have been using your plugin for a while now and it recently stopped working. this is the error:
`15/09/2020, 21:10:07 Error: watchpins helper error: Traceback (most recent call last):
  File "/home/hoobs/.hoobs/node_modules/homebridge-contactsensor/watchpins.py", line 13, in <module>
    if len(switches) == 0:
TypeError: object of type 'map' has no len()
)
    at Socket.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-contactsensor/contact.js:54:13)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
15/09/2020, 21:10:07 Got SIGTERM, shutting down Bridge...`

Hope you can help and it is a simple fix!

**Comment by brettferrell** [comment]
I get this as well.  I'm not a python guy, so there's probably a better way, but updated var/lib/homebridge-contactsensor/watchpins.py line 12 to the below and got it working

switches = [int(arg) for arg in sys.argv[1:]]
