### ISSUE TITLE
RuntimeError: No access to /dev/mem.

### ISSUE THREAD

**Issue by ageorgios** [rxseger/homebridge-contactsensor#6]
how to resolve? thank you!

```
/usr/lib/node_modules/homebridge-contactsensor/contact.js:54
Jul 04 21:11:10 rpi2 homebridge[1103]: throw new Error(`watchpins helper error: ${err})`);
Jul 04 21:11:10 rpi2 homebridge[1103]: ^
Jul 04 21:11:10 rpi2 homebridge[1103]: Error: watchpins helper error: Traceback (most recent call last):
Jul 04 21:11:10 rpi2 homebridge[1103]: File "/usr/lib/node_modules/homebridge-contactsensor/watchpins.py", line 24, in <module>
Jul 04 21:11:10 rpi2 homebridge[1103]: GPIO.setup(switches, GPIO.IN, pull_up_down=GPIO.PUD_UP)
Jul 04 21:11:10 rpi2 homebridge[1103]: RuntimeError: No access to /dev/mem.  Try running as root!
Jul 04 21:11:10 rpi2 homebridge[1103]: )
Jul 04 21:11:10 rpi2 homebridge[1103]: at Socket.ContactSensorPlugin.helper.stderr.on (/usr/lib/node_modules/homebridge-contactsensor/contact.js:54:13)
Jul 04 21:11:10 rpi2 homebridge[1103]: at emitOne (events.js:96:13)
Jul 04 21:11:10 rpi2 homebridge[1103]: at Socket.emit (events.js:191:7)
Jul 04 21:11:10 rpi2 homebridge[1103]: at readableAddChunk (_stream_readable.js:178:18)
Jul 04 21:11:10 rpi2 homebridge[1103]: at Socket.Readable.push (_stream_readable.js:136:10)
Jul 04 21:11:10 rpi2 homebridge[1103]: at Pipe.onread (net.js:561:20)
```

**Comment by ageorgios** [comment]
I think it fixed with:
`sudo adduser homebridge gpio`
